#!/usr/bin/env python3
"""Generate the all-campaign NetWaggle topology and N0/N1/N2 profiles."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "netwaggle/configs/site_evaluation_29node.json"
PROFILE_ROOT = ROOT / "netwaggle/configs/profiles/site_evaluation_29node"
ANCHOR_COMPOSE = ROOT / "netwaggle/compose.site_evaluation_29node.anchors.yaml"
ORINS = (1, 4, 7, *range(11, 31))
MOBILES = tuple(range(1, 7))


def sensor_link(switch: str) -> dict:
    return {
        "from": switch,
        "to": "s_edge",
        "bw": 100,
        "delay": "5ms",
        "jitter": "1ms",
        "loss": 0.1,
    }


def orin_node(number: int) -> dict:
    name = f"orin{number}"
    return {
        "name": name,
        "tier": "embedded",
        "anchor_container": f"netwaggle-node-{name}",
        "switch": f"s_{name}",
        "ip": f"10.255.{number}.2/16",
        "gateway": "10.255.0.1",
        "containers": [
            f"zed-replay-{name}",
            f"yolo-detector-{name}",
            f"respeaker-replay-{name}",
            f"audio-detector-{name}",
            f"fable-agent-{name}",
            f"fable-vehicle-{name}",
            f"fable-multimodal-{name}",
        ],
    }


def mobile_node(number: int) -> dict:
    name = f"mobile_archive_{number}"
    return {
        "name": name,
        "tier": "mobile",
        "anchor_container": f"netwaggle-node-{name}",
        # Mininet derives veth names from switch names. Linux IFNAMSIZ allows
        # only 15 characters, so keep the public node ID descriptive while
        # using a compact internal dataplane identifier.
        "switch": f"s_mob{number}",
        "ip": f"10.255.{100 + number}.2/16",
        "gateway": "10.255.0.1",
        "containers": [
            f"mobile-replay-{name}",
            f"yolo-detector-{name}",
            f"fable-agent-{name}",
            f"fable-vehicle-{name}",
            f"fable-multimodal-{name}",
        ],
    }


def write(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")


def write_anchor_compose(path: Path, nodes: list[dict]) -> None:
    """Write a standalone Compose file containing namespace anchors only."""

    services = {}
    for node in nodes:
        anchor = str(node["anchor_container"])
        services[anchor] = {
            "image": "fable/netwaggle-anchor:alpine3.20",
            "build": {"context": ".", "dockerfile": "Dockerfile.anchor"},
            "container_name": anchor,
            "command": [
                "sh",
                "-c",
                "iperf3 --server --daemon && trap : TERM INT; sleep infinity & wait",
            ],
            "network_mode": "none",
            "healthcheck": {
                "test": [
                    "CMD-SHELL",
                    "command -v ping >/dev/null && command -v iperf3 >/dev/null",
                ],
                "interval": "10s",
                "timeout": "3s",
                "retries": 3,
            },
        }
    path.write_text(
        "# Generated by scripts/generate_rq3a_network_topology.py\n"
        + json.dumps({"services": services}, indent=2)
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    sensors = [*(orin_node(number) for number in ORINS), *(mobile_node(number) for number in MOBILES)]
    links = [sensor_link(str(node["switch"])) for node in sensors]
    links.extend(
        (
            {
                "from": "s_edge",
                "to": "s_site",
                "bw": 1000,
                "delay": "0.5ms",
                "jitter": "0.1ms",
                "loss": 0,
            },
            {
                "from": "s_site",
                "to": "s_cloud",
                "bw": 200,
                "delay": "25ms",
                "jitter": "3ms",
                "loss": 0.1,
            },
        )
    )
    server_containers = [
        "fable-agent-x86server",
        "fable-identity-x86server",
        *(f"fable-vehicle-x86server-orin{number}" for number in ORINS),
    ]
    topology = {
        "schema_version": "fable.deployment_topology.v1",
        "name": "site-evaluation-29node",
        "device_count": len(sensors),
        "gateway": {
            "ip": "10.255.0.1/16",
            "switch": "s_cloud",
            "host_ifname": "nwg-host",
            "switch_ifname": "nwg-sw",
            "mtu": 1500,
        },
        "mqtt_host_ip": "10.255.0.1",
        "switches": [*(node["switch"] for node in sensors), "s_edge", "s_site", "s_cloud"],
        "links": links,
        "logical_nodes": [
            *sensors,
            {
                "name": "site_local",
                "tier": "server",
                "anchor_container": "netwaggle-node-site-local",
                "switch": "s_site",
                "ip": "10.255.240.2/16",
                "gateway": "10.255.0.1",
                "containers": server_containers,
            },
            {
                "name": "cloud1",
                "tier": "cloud",
                "anchor_container": "netwaggle-node-cloud1",
                "switch": "s_cloud",
                "ip": "10.255.250.2/16",
                "gateway": "10.255.0.1",
                "containers": [
                    "complex-event-detector",
                    "fable-agent-cloud1",
                    "fable-vlm-cloud1",
                ],
            },
        ],
    }
    n0 = {
        "schema_version": "netwaggle.profile.v1",
        "name": "N0",
        "topology": topology["name"],
        "links": links,
    }
    l1_links = [dict(row) for row in links]
    l1_links[0].update(
        bw=5, delay="40ms", jitter="10ms", loss=2, max_queue_size=100
    )
    l1 = {
        "schema_version": "netwaggle.profile.v1",
        "name": "L1",
        "topology": topology["name"],
        "links": l1_links,
    }
    n2_links = [dict(row) for row in links]
    backbone = next(
        row for row in n2_links if {row["from"], row["to"]} == {"s_edge", "s_site"}
    )
    backbone.update(
        bw=25, delay="20ms", jitter="5ms", loss=1, max_queue_size=100
    )
    n2 = {
        "schema_version": "netwaggle.profile.v1",
        "name": "N2",
        "topology": topology["name"],
        "links": n2_links,
    }
    write(OUTPUT, topology)
    write_anchor_compose(ANCHOR_COMPOSE, topology["logical_nodes"])
    write(PROFILE_ROOT / "N0.json", n0)
    write(PROFILE_ROOT / "L1.json", l1)
    write(PROFILE_ROOT / "N2.json", n2)
    write(
        PROFILE_ROOT / "CONDITION_MAP.json",
        {
            "schema_version": "netwaggle.condition_map.v1",
            "conditions": {"N0": "N0.json", "L1": "L1.json", "N2": "N2.json"},
        },
    )
    print(
        json.dumps(
            {
                "topology": str(OUTPUT),
                "profile_root": str(PROFILE_ROOT),
                "sensor_nodes": len(sensors),
                "links": len(links),
                "anchor_compose": str(ANCHOR_COMPOSE),
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
